apiVersion: v1
kind: Service
metadata: 
  name: sample-svc
  labels:
    app: sample-java
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
    app: sample-java
